FROM ubuntu:jammy AS build

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

ARG NUM_CORES

RUN apt-get clean && apt-get update

RUN apt-get install -y \
    tzdata \
    software-properties-common \
    manpages-dev \
    build-essential \
    libcurl4-openssl-dev \
    libssl-dev \
    liblzma-dev \
    python3 \
    python3-venv \
    python-dev-is-python3 \
    python3-pip \
    git \
    wget \
    tar \
    lld

# Create and navigate to the src directory
RUN mkdir /src
WORKDIR /src

# Clone the MongoDB repository
RUN git clone https://github.com/mongodb/mongo.git

WORKDIR /src/mongo
RUN git checkout r8.0.4

# Apply patches
COPY patches/*.patch /src/mongo
RUN for patch in $(ls *.patch | sort); do patch -p0 < $patch; done

# Set up Python virtual environment and install requirements
RUN python3 -m venv .venv --prompt mongo && . .venv/bin/activate
RUN pip install 'poetry==1.5.1'
RUN poetry install --no-root --sync

# Build MongoDB
RUN . .venv/bin/activate && \
    python3 buildscripts/scons.py install-mongod \
    -j$NUM_CORES \
    --release \
    --dbg=off \
    --disable-warnings-as-errors \
    --experimental-optimization=-sandybridge \
     CCFLAGS="-march=nehalem"


# Copy the built mongod to /tmp/output
RUN mkdir -p /tmp/output && \
    cd build/install/bin/ && \
    cp mongod /tmp/output/mongod

FROM ubuntu:jammy AS package

ARG REV

RUN apt-get clean && apt-get update && apt-get install -yq wget lsb-release

COPY --from=build /tmp/output/mongod /tmp/mongod

WORKDIR /tmp

RUN wget -O /etc/apt/trusted.gpg.d/efs.gpg  https://download.slc.efscloud.net/replibit/efs.gpg && chmod 0666 /etc/apt/trusted.gpg.d/efs.gpg

RUN echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu jammy main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list

RUN echo "deb https://rb-mirror.slc.efscloud.net/repo.replibit.net jammy-rb main" > /etc/apt/sources.list.d/replibit.list

RUN apt update

RUN apt download mongodb-8.0-jammy-server

RUN mkdir -p /tmp/custom-mongo

RUN dpkg-deb -R mongodb-8.0-jammy-server*.deb /tmp/custom-mongo

WORKDIR /tmp/custom-mongo

# replace mongod with the one we built
RUN cp /tmp/mongod ./usr/bin/mongod

# remove mongod.service
RUN rm -rf ./lib

# add axcient version
RUN sed -i 's/Version: 8.0.4/Version: 8.0.4-ubuntu'$REV'~'$(lsb_release -r -s)'/g' DEBIAN/control

# repack the deb
RUN dpkg-deb -b /tmp/custom-mongo /tmp/mongodb-8.0-jammy-server-custom.deb
