FROM ubuntu:focal AS mongo-src

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

ARG CPU_ARCH=nehalem

RUN echo "CPU Architecture: ${CPU_ARCH}"

RUN apt-get clean && apt-get update && apt-get install -y  \
    git \
    tzdata \
    software-properties-common \
    manpages-dev \
    build-essential \
    libcurl4-openssl-dev \
    libssl-dev \
    liblzma-dev


RUN mkdir /src
WORKDIR /src

COPY . /src

RUN git submodule update --init --remote --checkout mongo

WORKDIR /src/mongo

RUN git checkout r8.0.4

# Create patches directory
COPY patches /src/mongo/patches
# Copy architecture-specific patches if applicable
RUN if [ "$CPU_ARCH" = "core2" ]; then \
        cp patches/${CPU_ARCH}/*.patch patches ; \
    fi

# Apply patches
RUN for patch in $(ls patches/*.patch | sort); do patch -p0 < $patch; done


FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

ARG NUM_CORES
ARG CPU_ARCH=nehalem

ENV CCFLAGS="-march=${CPU_ARCH}"

# Copy only the mongo source
COPY --from=mongo-src /src /src

WORKDIR /src/mongo

RUN apt-get clean && apt-get update

RUN apt-get install -y \
    tzdata \
    software-properties-common \
    manpages-dev \
    build-essential \
    libcurl4-openssl-dev \
    libssl-dev \
    liblzma-dev \
    python3 \
    python3-venv \
    python-dev-is-python3 \
    python3-pip \
    git \
    wget \
    tar \
    zip \
    lld

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BA6932366A755776
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2C277A0A352154E5

RUN echo "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main" > /etc/apt/sources.list.d/deadsnakes.list
RUN echo "deb http://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu focal main" > /etc/apt/sources.list.d/ubuntu-toolchain-r.list

RUN apt-get update

# python 3.10 and GCC 11 are required for building MongoDB 8
RUN apt install -y gcc-11  \
    g++-11  \
    python3.10  \
    python3.10-venv  \
    python3.10-dev

RUN update-alternatives --remove-all cpp
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9  --slave /usr/bin/cpp cpp /usr/bin/cpp-9
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11  --slave /usr/bin/cpp cpp /usr/bin/cpp-11

#
# Set up Python virtual environment and install requirements
RUN python3.10 -m venv .venv --prompt mongo && . .venv/bin/activate
RUN pip install 'poetry==1.5.1'
RUN poetry install --no-root --sync

# Build MongoDB
RUN . .venv/bin/activate && \
    python3 buildscripts/scons.py install-mongod \
    -j$NUM_CORES \
    --release \
    --dbg=off \
    --disable-warnings-as-errors \
    --experimental-optimization=-sandybridge \
    CCFLAGS="${CCFLAGS}"

RUN mkdir -p /tmp/output && \
    cd build/install/bin/ && \
    cp mongod /tmp/output/mongod

RUN cd /tmp/output && \
    zip -r mongod.zip mongod
