FROM ubuntu:focal AS build

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

ARG NUM_CORES

RUN apt-get clean && apt-get update

RUN apt-get install -y \
    tzdata \
    software-properties-common \
    manpages-dev \
    build-essential \
    libcurl4-openssl-dev \
    libssl-dev \
    liblzma-dev \
    python3 \
    python3-venv \
    python-dev-is-python3 \
    python3-pip \
    git \
    wget \
    tar \
    zip \
    lld

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BA6932366A755776
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2C277A0A352154E5

RUN echo "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main" > /etc/apt/sources.list.d/deadsnakes.list
RUN echo "deb http://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu focal main" > /etc/apt/sources.list.d/ubuntu-toolchain-r.list

RUN apt-get update

RUN apt install -y gcc-11  \
    g++-11  \
    python3.10  \
    python3.10-venv  \
    python3.10-dev

RUN update-alternatives --remove-all cpp
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9  --slave /usr/bin/cpp cpp /usr/bin/cpp-9
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11  --slave /usr/bin/cpp cpp /usr/bin/cpp-11

# Create and navigate to the src directory
RUN mkdir /src
WORKDIR /src

# Clone the MongoDB repository
RUN git clone https://github.com/mongodb/mongo.git

WORKDIR /src/mongo
RUN git checkout r8.0.4

# Apply patches
COPY patches/*.patch /src/mongo
RUN for patch in $(ls *.patch | sort); do patch -p0 < $patch; done

# Set up Python virtual environment and install requirements
RUN python3.10 -m venv .venv --prompt mongo && . .venv/bin/activate
RUN pip install 'poetry==1.5.1'
RUN poetry install --no-root --sync

# Build MongoDB
RUN . .venv/bin/activate && \
    python3 buildscripts/scons.py install-mongod \
    -j$NUM_CORES \
    --release \
    --dbg=off \
    --disable-warnings-as-errors \
    --experimental-optimization=-sandybridge \
     CCFLAGS="-march=nehalem"


# Copy the built mongod and libstdc++.so.6 to /tmp/output
RUN mkdir -p /tmp/output && \
    cd build/install/bin/ && \
    cp mongod /tmp/output/mongod && \
    cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32 /tmp/output/libstdc++.so.6


FROM ubuntu:focal AS package

ARG REV

RUN apt-get clean && apt-get update && apt-get install -yq wget lsb-release

COPY --from=build /tmp/output/mongod /tmp/mongod
COPY --from=build "/tmp/output/libstdc++.so.6" "/tmp/libstdc++.so.6"

WORKDIR /tmp

RUN wget -O /etc/apt/trusted.gpg.d/efs.gpg  https://download.slc.efscloud.net/replibit/efs.gpg && chmod 0666 /etc/apt/trusted.gpg.d/efs.gpg

RUN echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu focal main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu focal-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu focal-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] https://rb-mirror.slc.efscloud.net/ubuntu focal-backports main restricted universe multiverse" >> /etc/apt/sources.list

RUN echo "deb https://rb-mirror.slc.efscloud.net/repo.replibit.net focal-rb main" > /etc/apt/sources.list.d/replibit.list

RUN apt update

RUN apt download mongodb-8.0-server

RUN mkdir -p /tmp/custom-mongo

RUN dpkg-deb -R mongodb-8.0-server*.deb /tmp/custom-mongo

WORKDIR /tmp/custom-mongo

# Place /tmp/libstdc++.so.6 in /tmp/custom-mongo/opt/replibit/lib/libstdc++.so.6
RUN mkdir -p ./opt/replibit/lib

RUN cp /tmp/libstdc++.so.6 ./opt/replibit/lib/libstdc++.so.6

# replace mongod with the one we built
RUN cp /tmp/mongod ./usr/bin/mongod

# remove mongod.service
RUN rm -rf ./lib

RUN sed -i 's/Package: mongodb-8.0-server/Package: mongodb-8.0-focal-server/g' DEBIAN/control

# add axcient version
RUN sed -i 's/Version: 8.0.4/Version: 8.0.4-ubuntu'$REV'~'$(lsb_release -r -s)'/g' DEBIAN/control

# repack the deb
RUN dpkg-deb -b /tmp/custom-mongo /tmp/mongodb-8.0-focal-server-custom.deb
